---
development:
  cloud_name: feiy
  api_key: '719846177685721'
  api_secret: KZfEog-gi9ZjP15Nh9-tdtfBNZA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: feiy
  api_key: '719846177685721'
  api_secret: KZfEog-gi9ZjP15Nh9-tdtfBNZA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: feiy
  api_key: '719846177685721'
  api_secret: KZfEog-gi9ZjP15Nh9-tdtfBNZA
  enhance_image_tag: true
  static_file_support: false
