development:
  cloud_name: dt8zkhia0
  api_key: '557984143875435'
  api_secret: RjrN2sH5ZXO2JZHGayZkA5FuOvc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dt8zkhia0
  api_key: '557984143875435'
  api_secret: RjrN2sH5ZXO2JZHGayZkA5FuOvc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dt8zkhia0
  api_key: '557984143875435'
  api_secret: RjrN2sH5ZXO2JZHGayZkA5FuOvc
  enhance_image_tag: true
  static_image_support: false
